config/routes.rb
ClicouBeleza::Application.routes.draw do

  scope :user do
    devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks" }
    resources :venues
    resources :posts
    resources :profile, only: [:show] do
      post 'follow', on: :member
      get 'unfollow', on: :member
      get 'posts', on: :member
    end

    resources :dashboard, only: [:index, :show] do
      get 'love', on: :member
      post 'comment', on: :member
    end
  end

  root :to => 'home#index'

  resources :followings
  resources :comments
  resources :loveds
  resources :home, only: :index

end
#== Route Map
# Generated on 27 Mai 2013 13:21
#
#             user_session POST   /users/sign_in(.:format)               users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              users/sessions#destroy
#  user_omniauth_authorize        /users/auth/:provider(.:format)        users/omniauth_callbacks#passthru {:provider=>/(?!)/}
#   user_omniauth_callback        /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:(?!))
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#        user_registration POST   /users(.:format)                       devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                          PUT    /users(.:format)                       devise/registrations#update
#                          DELETE /users(.:format)                       devise/registrations#destroy
#                   venues GET    /venues(.:format)                      venues#index
#                          POST   /venues(.:format)                      venues#create
#                new_venue GET    /venues/new(.:format)                  venues#new
#               edit_venue GET    /venues/:id/edit(.:format)             venues#edit
#                    venue GET    /venues/:id(.:format)                  venues#show
#                          PUT    /venues/:id(.:format)                  venues#update
#                          DELETE /venues/:id(.:format)                  venues#destroy
#                     root        /                                      home#index
#               home_index GET    /home(.:format)                        home#index
#            venues2_index GET    /venues2(.:format)                     venues2#index

app/controllers/dashboard_controller.rb
class DashboardController < UserController
  skip_before_filter :authenticate_user!, only: [:index, :show]
  respond_to :html, :json
  def index
    if params[:source] == 'user'
      @posts = current_user.posts.order("created_at desc").paginate(page: params[:page], per_page: 15)
    elsif params[:source] == 'loved'
      @posts = current_user.loved_posts.order("created_at desc").paginate(page: params[:page], per_page: 15)
    else
      @posts = Post.order("created_at desc").paginate(page: params[:page], per_page: 15)
    end
    @posts = @posts.where("categories like ?", "%#{params[:category]}%") if params[:category].present?
    
    @posts.each_with_index do |p, idx|
      @posts[idx]["user_avatar"] = p.user.avatar.url(:medium)
      @posts[idx]["user_name"] = p.user.name
    end
    
    respond_with @posts, methods: :photo_urls
  end

  def love
    @loved = current_user.loveds.find_or_initialize_by_post_id(params[:id])
    if @loved.persisted?
      @loved.destroy
      respond_with ['unloved']
    else
      @loved.post_id = params[:id]
      if @loved.save
        respond_with ['loved']
      else
        respond_with @loved.errors, status: 400
      end
    end
  end

  def comment
    @comment = current_user.comments.new(params[:comment])
    @comment.post_id = params[:id]

    if @comment.save
      respond_with @comment
    else
      respond_with @comment, status: 400
    end
  end

  def show

    @comment = Comment.new

    @post = Post.find(params[:id])
    
    @post[:user_avatar] = @post.user.avatar.url(:medium)
    @post[:user_name] = @post.user.name
    
    respond_with @post, methods: :photo_urls, include: {
        loveds: { only: [:id, :created_at], include: { user: { only: [:id, :name], methods: :avatar_urls } } } ,
        comments: { only: [:id, :created_at, :comment], include: { user: { only: [:id, :name], methods: :avatar_urls } } }
    }
  end
end

app/views/dashboard/index.html.haml
= javascript_include_tag "dashboard"
.content-body.dashboard
  - @posts.each do |post|
    = div_for post do
      .user
        = link_to profile_path(post.user) do
          = image_tag post.user.avatar.url(:thumb)
          %strong= post.user
      .photo
        = link_to dashboard_path(post) do
          = image_tag post.photo.url(:cropped)
      .description= post.description
      .options
        .venue
          %strong= post.venue_info
        .loveds
          %a{ data: { href: love_dashboard_path(post.id, format: :json) } }= post.loveds.size
        .comments
          = post.comments.size
        .clearfix

app/views/dashboard/show.html.haml
= javascript_include_tag "posts"
.content-body.dashboard
  = div_for @post do
    .user
      = image_tag @post.user.avatar.url(:thumb)
      %strong= @post.user
    .photo= image_tag @post.photo.url(:cropped)
    .description= @post.description
    .options
      .venue
        %strong= @post.venue_info
      .loveds
        = link_to @post.loveds.size, love_dashboard_path(@post.id), remote: true
      .comments
        = @post.comments.size
      .clearfix

  - @post.comments.each do |comment|
    = div_for comment, class: 'media' do
      = link_to profile_path(comment.user), class: 'pull-left' do
        = image_tag comment.user.avatar.url(:thumb)
      .media-body
        %h5.media-heading= comment.user
        %span= comment.comment

  .clearfix
  = simple_form_for(@comment, url: comment_dashboard_path(@post.id, format: :json), remote: true, defaults: { input_html: { class: 'form-horizontal' } }) do |f|
    = f.error_notification
    = f.input :post_id, as: :hidden, value: @post.id
    = f.input :comment, as: :text
    = f.submit :submit