config/routes.rb
ClicouBeleza::Application.routes.draw do

  scope :user do
    devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks" }
    resources :venues
    resources :posts
    resources :profile, only: [:show] do
      post 'follow', on: :member
      get 'unfollow', on: :member
      get 'posts', on: :member
    end

    resources :dashboard, only: [:index, :show] do
      get 'love', on: :member
      post 'comment', on: :member
    end
  end

  root :to => 'home#index'

  resources :followings
  resources :comments
  resources :loveds
  resources :home, only: :index

end
#== Route Map
# Generated on 27 Mai 2013 13:21
#
#             user_session POST   /users/sign_in(.:format)               users/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)              users/sessions#destroy
#  user_omniauth_authorize        /users/auth/:provider(.:format)        users/omniauth_callbacks#passthru {:provider=>/(?!)/}
#   user_omniauth_callback        /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:(?!))
#            user_password POST   /users/password(.:format)              devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                          PUT    /users/password(.:format)              devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#        user_registration POST   /users(.:format)                       devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                          PUT    /users(.:format)                       devise/registrations#update
#                          DELETE /users(.:format)                       devise/registrations#destroy
#                   venues GET    /venues(.:format)                      venues#index
#                          POST   /venues(.:format)                      venues#create
#                new_venue GET    /venues/new(.:format)                  venues#new
#               edit_venue GET    /venues/:id/edit(.:format)             venues#edit
#                    venue GET    /venues/:id(.:format)                  venues#show
#                          PUT    /venues/:id(.:format)                  venues#update
#                          DELETE /venues/:id(.:format)                  venues#destroy
#                     root        /                                      home#index
#               home_index GET    /home(.:format)                        home#index
#            venues2_index GET    /venues2(.:format)                     venues2#index

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  venue_id   :integer
#  deleted_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Venue < ActiveRecord::Base

  acts_as_paranoid

  attr_accessible :deleted_at, :name, :venue_id

  validates :name, :venue_id, presence: true

  validates :name, length: { maximum: 255 }

  def to_s
    name
  end

end

app/controllers/venues_controller.rb
class VenuesController < UserController

  def index
    client = Foursquare2::Client.new(:client_id => '3JLPOEMCQ05BHK3LAOL0ANTXT1KKYHXDKKAFAPTKR3IAD2E3', :client_secret => 'QSYLJVS0OCDFNTKZ1DZ2IL1BQVKTCCYQ1LVRIPZORSLF503Z')

    ll = params[:ll] || '-16.6723002,-49.2783986'
    query = params[:query] || ''
    category_id = '4f04aa0c2fb6e1c99f3db0b8,4bf58dd8d48988d110951735,4d1cf8421a97d635ce361c31,4bf58dd8d48988d1ed941735'

    @venue_categories = client.venue_categories
    @venues = client.search_venues(ll: ll, query: query, categoryId: category_id).groups.first.items

    respond_to do |format|
      format.html
      format.json { render json: @venues }
    end
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def new
    @venue = Venue.new
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: t('controllers.action.success.create') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: t('controllers.action.success.update') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy
    
    redirect_to venues_url
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
  def venue_location(location)
    location.values.to_sentence
  end
end

app/views/venues/_form.html.haml
= simple_form_for(@venue, defaults: { input_html: { class: 'form-horizontal' } }) do |f|
  = f.error_notification
  = f.input :name
  = f.input :venue_id
  = f.input :deleted_at
  .form-actions
    = f.button :submit, :class => "btn-primary"

app/views/venues/edit.html.haml
.content-header
  .pull-left
    %h2 #{t('actions.edit')} #{t('activerecord.models.venue').downcase} - #{@venue}
  .pull-right
    .btn-group
      = link_to venues_path, class: 'btn', title: t('actions.back') do
        %i.icon-arrow-left
      = link_to @venue, class: 'btn tip-bottom', title: t('actions.show') do
        %i.icon-eye-open
      = link_to new_venue_path, class: 'btn btn-success', title: "#{t('actions.create')} #{t('activerecord.models.venue').downcase}" do
        %i.icon-plus.icon-white
  .clearfix
  
%ul.breadcrumb
  %li
    = link_to t('views.home'), root_path
    %span.divider /
  %li
    = link_to t('activerecord.models.venue').pluralize, venues_path
    %span.divider /
  %li.active #{t('actions.edit')} #{t('activerecord.models.venue').downcase} - #{@venue}

.content-body
  = render 'form'

app/views/venues/index.html.haml
.content-header
  .pull-left
    %h2= t('activerecord.models.venue').pluralize
  .pull-right
    = link_to new_venue_path, class: 'btn btn-success', title: "#{t('actions.create')} #{t('activerecord.models.venue').downcase}" do
      %i.icon-plus.icon-white
  .clearfix
  %ul.breadcrumb
    %li
      = link_to t('views.home'), root_path
      %span.divider /
    %li.active= t('activerecord.models.venue').pluralize
  
.content-body
  - if @venues.any?
    %table.table.table-bordered
      %thead
        %tr
          %th= t('activerecord.attributes.venue.name')
          %th= t('activerecord.attributes.venue.venue_id')
          %th= t('activerecord.attributes.venue.deleted_at')
          %th= t('words.actions')
      %tbody
        - @venues.each do |venue|
          %tr
            %td= venue.name
            %td= venue_location(venue.location)
            %td= venue.to_json

app/views/venues/new.html.haml
.content-header
  .pull-left
    %h2 #{t('actions.create')} #{t('activerecord.models.venue').downcase}
  .pull-right
    = link_to venues_path, class: 'btn tip-bottom', title: t('actions.back') do
      %i.icon-arrow-left
  .clearfix
  %ul.breadcrumb
    %li
      = link_to t('views.home'), root_path
      %span.divider /
    %li
      = link_to t('activerecord.models.venue').pluralize, venues_path
      %span.divider /
    %li.active #{t('actions.create')} #{t('activerecord.models.venue').downcase}  
         
.content-body
  = render 'form'

app/views/venues/show.html.haml
.content-header
  .pull-left
    %h2 #{t('activerecord.models.venue')} - #{@venue}
  .pull-right
    .btn-group
      = link_to venues_path, class: 'btn', title: t('actions.back') do
        %i.icon-arrow-left
      = link_to edit_venue_path(@venue), class: 'btn', title: t('actions.edit') do
        %i.icon-edit
      = link_to new_venue_path, class: 'btn btn-success', title: "#{t('actions.create')} #{t('activerecord.models.venue').downcase}" do
        %i.icon-plus.icon-white
  .clearfix
  %ul.breadcrumb
    %li
      = link_to t('views.home'), root_path
      %span.divider /
    %li
      = link_to t('activerecord.models.venue').pluralize, venues_path
      %span.divider /
    %li.active #{t('activerecord.models.venue')} - #{@venue} 
  
.content-body
  %dt= t('activerecord.attributes.venue.name')
  %dd= @venue.name
  %dt= t('activerecord.attributes.venue.venue_id')
  %dd= @venue.venue_id
  %dt= t('activerecord.attributes.venue.deleted_at')
  %dd= @venue.deleted_at
  